apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-ui-deployment
spec:
  replicas: 2 # Number of desired pods
  selector:
    matchLabels:
      app: restaurant-ui
  template:
    metadata:
      labels:
        app: restaurant-ui
    spec:
    
      containers:
        - name: restaurant-ui-container
          image: wisewizard123/restaurant-ui:latest # Replace with your Docker image and tag
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-ui-service
spec:
  selector:
    app: restaurant-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer # Expose as LoadBalancer or NodePort, depending on your setup
